				{
					connectingLane {
						lane [CONNECT_LANE_ID],
						maneuver {[CONNECT_MANEUVER_TYPE]}
					},
					remoteIntersection {
						id [REMOTE_INTERSECTION_ID]
					},
					signalGroup [CONNECT_SIGNAL_GROUP],
					connectionID [CONNECTION_ID]
				}